FROM quay.io/centos/centos:stream9-minimal

RUN /usr/bin/microdnf -y install python3.12 python3.12-pip \
 && /usr/bin/microdnf clean all \
 && /usr/sbin/alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1 \
                           --follower /usr/bin/pip3 pip3 /usr/bin/pip3.12 \
 && /usr/bin/pip3 install boto3 pandas numpy scipy \
 && /usr/bin/pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu \
 && /usr/bin/mkdir -p /opt/app-root/src \
 && /usr/bin/chgrp -R 0 /opt/app-root/src \
 && /usr/bin/chmod -R g=u /opt/app-root/src

WORKDIR /opt/app-root/src
